project:
  type: website

website:
  title: "Josh M. Ryan"
  google-analytics: "G-NGT9J688G5"
  navbar:
    left:
      - href: publications.qmd
        text: Journal Articles
      - href: working_papers.qmd
        text: Working Papers
      - href: votes_data.qmd
        text: House Committee Votes Data
      - href: textbook.qmd
        text: American Politics Textbook
      - href: teaching.qmd
        text: Teaching
      - href: media.qmd
        text: Media
      - href: Ryan_External_CV.pdf
        text: CV
format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    mainfont: $font-family-sans-serif

editor: visual






