---
title: "About"
---

I am Associate Professor of Political Science at Utah State University in Logan, UT. My research focuses on American institutions, especially Congress, the president, state legislatures and executives, as well as electoral institutions. I am interested in the policy process, bicameral dynamics, legislative productivity, and agenda formation in legislatures, and how institutions structure representation and elite behavior.

My research has been published in *The Journal of Politics*, *Legislative Studies Quarterly*, *Political Science Research and Methods*, and *Political Research Quarterly*, among other outlets. My book, [The Congressional Endgame: Interchamber Bargaining and Resolution](https://press-uchicago-edu.dist.lib.usu.edu/ucp/books/book/chicago/C/bo28907983.html), published by the University of Chicago Press, explores the postpassage bargaining process in Congress. I have twice (2016, 2021) been awarded the Jewell-Loewenberg Award for the best article published on American politics in Legislative Studies Quarterly.

At Utah State, I enjoy teaching courses on American politics and research methods. I seek to emphasize how social science can help us understand fundamental questions about the American political system. I also encourage students to participate in the research process, and have had a number of undergraduate and graduate students participate at national conferences and admitted to Ph.D. programs.

I am originally from Southern California and majored in political science and minored in Spanish literature at UCSD. I attended UCDC and interned on Capitol Hill for the [Environmental and Energy Study Institute](https://www.eesi.org/). Prior to becoming a political scientist, I worked as a contractor for HUD in Los Angeles conducting compliance reviews of project-based Section 8 housing. In my free time I enjoy bicycling, fishing, and Padres baseball.
