baseurl: '/'
languageCode: 'en-us'
title: 'Josh M. Ryan'
theme: 'hugo-lithium'

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: 'Home'
      url: '/'
    - name: 'Publications'
      url: '/publications/'
    - name: 'Working Papers'
      url: '/working_papers/'
    - name: 'Data'
      url: '/data/'
    - name: 'Textbook'
      url: '/textbook/'
    - name: 'Teaching'
      url: '/teaching/'
    - name: 'Media'
      url: '/media/'
    - name: 'CV'
      url: '/Ryan_External_CV.pdf'

params:
  description: 'Josh M. Ryan - Associate Professor of Political Science'
