---
title: "Media/Public Facing Contributions"
---

-   [Interviewed by the American Enterprise Institute's "Understanding Congress" podcast with Kevin Kosar, May 2022](https://www.aei.org/podcast/what-is-a-conference-committee-and-why-are-they-so-rare-today-with-josh-ryan/)

-   [Interviewed by The New York Times on Gov. Cox's veto of the transgender athlete bill on March 22, 2022](https://www.nytimes.com/2022/03/22/us/utah-governor-transgender-athlete-ban.html)

-   [Interviewed by Fox 13 News, Salt Lake City: FOX 13 Investigates: Utahns continued donating millions to Donald Trump after the election, April 28, 2021](https://www.youtube.com/watch?v=Q-4opejcvm8)

-   [Interviewed by Politifact.com on the the budget reconciliation process on February 8, 2021](https://www.politifact.com/article/2021/feb/08/what-you-need-know-about-budget-reconciliation-pro/)

-   [Interviewed by Politifact.com on the \`\`talking filibuster" on March 9, 2021](https://www.politifact.com/article/2021/mar/09/would-talking-filibuster-get-senate-moving/)

-   [Interviewed on Biden's Immigration Plan by the Moutain West News Bureau Public Radio on January 26, 2021](https://www.wyomingpublicmedia.org/2021-01-26/biden-immigration-plan-would-give-nearly-600-000-in-the-mountain-west-a-path-to-citizenship)

-   [Interviewed by Politifact.com on the a 50-50 split in the Senate on January 7, 2021](https://www.politifact.com/article/2021/jan/07/how-will-senate-work-under-50-50-tie/)

-   [Participant, "The Presidency", sponsored by the Hinckley Institute at the University of Utah.} Sept. 22, 2020](https://www.hinckley.utah.edu/calendar/2020/9/22/the-presidency)

-   [Interviewed by Politifact.com on the passage of the CARES Act, April 27, 2020](https://bit.ly/2VFrfUI)

-   Live in-studio commentary on impeachment inquiry, September 27, 2019, Fox 13 News, Salt Lake City

-   Interviewed about impeachment inquiry, September 26, 2019. Fox 13 News, Salt Lake City

-   [Interviewed by Politifact.com on the Hyde Amendment on June 11, 2019](https://www.politifact.com/truth-o-meter/statements/2019/jun/11/bernie-sanders/bernie-sanders-oversimplifies-record-hyde-amendmen/)

-   [Interviewed by the Deseret News on Abortion Protests at the Utah State Capitol on May 21, 2019](https://www.deseretnews.com/article/900071694/hundreds-in-utah-join-nationwide-abortion-law-protests.html)

-   [Interviewed by Politifact.com on the government shutdown on January 17, 2019](https://www.politifact.com/truth-o-meter/article/2019/jan/17/your-questions-about-government-shutdown-answered-/)

-   [Interviewed by Politifact.com on voting records and government shutdowns on August 6, 2018](https://www.politifact.com/truth-o-meter/statements/2018/aug/06/kevin-cramer/kevin-cramer-distorts-shutdown-record/)

-   Coverage of committee partisanship research on [Legbranch.org](https://www.legbranch.org/2018-5-17-how-partisan-are-house-committees-and-does-it-matter-for-lawmaking/) and [Bloomberg News](https://www.bloomberg.com/opinion/articles/2018-05-17/democrats-should-consider-a-boring-traditional-presidential-nod), May 2018

-   [Interviewed by Politifact.com on Florida Senator Bill Nelson's legislative productivity on April 11 and April 19, 2018](https://tinyurl.com/yahrsct8)

-   [Interviewed by Politifact.com on the government shutdown on January 22, 2018 and previous shutdowns January 22, 2018](https://tinyurl.com/y9qvyt43)

-   Interviewed by Politifact.com on the health care repeal bill, Senate procedures, and conference committees on [July 26, 2017](http://tinyurl.com/y9fzpfmn) and [July 30, 2017](http://tinyurl.com/ybbf8m4o)

-   Interviewed by the Daily Briefing, The Advisory Board Company's health care newsletter on the health care repeal bill and the reconciliation process, July 31, 2017

-   [Coverage of redistricting research in Chicago Tribune, June 5, 2015](http://www.chicagotribune.com/news/opinion/commentary/ct-maps-perspec-0608-20150608-story.html)

-   [Coverage of gubernatorial veto powers research in Chicago Tribune, May 2, 2014](http://articles.chicagotribune.com/2014-05-02/opinion/ct-illinois-amendments-governor-zorn-0502-jm-20140502_1_governor-bruce-rauner-term-limits)

-   Media coverage of *Reconsidering the \`Palin Effect' in 2008* in [Peoria-Journal Star](http://www.pjstar.com/article/20131208/NEWS/131209293), the Washington Examiner and other outlets, November and December 2013

-   Interviewed by WMBD 1470 Talk Station, February 24, 2012, August 24, 2012, and November 21, 2014

-   Live in-studio commentary and analysis: elections and registration process, October 28, 2013; the third presidential debate, October 22, 2012; Illinois primary election night, March 20, 2012. WMBD-31, Peoria/Bloomington

-   Interviewed by WHOI-19, Peoria/Bloomington, numerous occasions

-   Interviewed by WMBD-31 Peoria/Bloomington, numerous occasions

-   Interviewed by Peoria-Journal Star, numerous occasions

-   [Interviewed by Chicago Sun-Times on Aaron Schock corruption charges, March 9, 2015](http://chicago.suntimes.com/news/aaron-schock-repays-taxpayers-after-sun-times-story-on-private-plane-trip-to-bears-game/)
